definitions:
  dto.ErrorResponse:
    description: Error response structure
    properties:
      message:
        type: string
    type: object
  dto.GetUserResponse:
    description: User response data
    properties:
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by their ID from the gRPC service
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get a user by ID
      tags:
      - Users
swagger: "2.0"
