name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env files for services
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

          echo "USER_RPC_ADDRESS=${{ secrets.USER_RPC_ADDRESS }}" > ./api-gateway/.env
          echo "BOOK_RPC_ADDRESS=${{ secrets.BOOK_RPC_ADDRESS }}" >> ./api-gateway/.env
          echo "AUTHOR_RPC_ADDRESS=${{ secrets.AUTHOR_RPC_ADDRESS }}" >> ./api-gateway/.env
          echo "CATEGORY_RPC_ADDRESS=${{ secrets.CATEGORY_RPC_ADDRESS }}" >> ./api-gateway/.env
          echo "APP_PORT=${{ secrets.APP_PORT }}" >> ./api-gateway/.env
          echo "GRPC_PORT=${{ secrets.GRPC_PORT }}" >> ./api-gateway/.env
          echo "SERVICE_NAME=${{ secrets.SERVICE_NAME_API_GATEWAY }}" >> ./api-gateway/.env

          echo "DB_HOST=${{ secrets.DB_HOST }}" > ./user-service/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./user-service/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./user-service/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./user-service/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> ./user-service/.env
          echo "GRPC_PORT=${{ secrets.GRPC_PORT }}" >> ./user-service/.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> ./user-service/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ./user-service/.env
          echo "SECRET_JWT=${{ secrets.SECRET_JWT }}" >> ./user-service/.env
          echo "SERVICE_NAME=${{ secrets.SERVICE_NAME_USER_SERVICE }}" >> ./user-service/.env
          echo "BOOK_RPC_ADDRESS=${{ secrets.BOOK_RPC_ADDRESS }}" >> ./user-service/.env

          echo "DB_HOST=${{ secrets.DB_HOST }}" > ./book-service/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./book-service/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./book-service/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./book-service/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> ./book-service/.env
          echo "GRPC_PORT=${{ secrets.GRPC_PORT }}" >> ./book-service/.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> ./book-service/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ./book-service/.env
          echo "SERVICE_NAME=${{ secrets.SERVICE_NAME_BOOK_SERVICE }}" >> ./book-service/.env
          echo "USER_RPC_ADDRESS=${{ secrets.USER_RPC_ADDRESS }}" >> ./book-service/.env

          echo "DB_HOST=${{ secrets.DB_HOST }}" > ./author-service/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./author-service/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./author-service/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./author-service/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> ./author-service/.env
          echo "GRPC_PORT=${{ secrets.GRPC_PORT }}" >> ./author-service/.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> ./author-service/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ./author-service/.env
          echo "SERVICE_NAME=${{ secrets.SERVICE_NAME_AUTHOR_SERVICE }}" >> ./author-service/.env

          echo "DB_HOST=${{ secrets.DB_HOST }}" > ./category-service/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> ./category-service/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ./category-service/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> ./category-service/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> ./category-service/.env
          echo "GRPC_PORT=${{ secrets.GRPC_PORT }}" >> ./category-service/.env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> ./category-service/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> ./category-service/.env
          echo "SERVICE_NAME=${{ secrets.SERVICE_NAME_CATEGORY_SERVICE }}" >> ./category-service/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Gateway image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/library-management:api-gateway-latest

      - name: Build and push User Service image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.user-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/library-management:user-service-latest

      - name: Build and push Book Service image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.book-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/library-management:book-service-latest

      - name: Build and push Author Service image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.author-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/library-management:author-service-latest

      - name: Build and push Category Service image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.category-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/library-management:category-service-latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd library-management
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            docker-compose pull
            docker-compose up -d --build
